version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_USER: username 
      MYSQL_PASSWORD: password  
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql 
  web:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - .:/app

volumes:
  db_data:
    
    

